### ISSUE TITLE
下载链接有问题

### ISSUE THREAD

**Issue by gstory0404** [treexi/wework#15]
设置APP_SPA_DOMAIN后下载链接变为https://xxx.com/本机ip/xxx.apk, 正常应该为 https://xxx.com/xxx.apk 不知道为何这里会追加一个本机的ip

**Comment by treexi** [comment]
源码部署的吗？

**Comment by gstory0404** [comment]
本地编译dockerfile部署

**Comment by treexi** [comment]
用源码吧 docker 没维护了
