### ISSUE TITLE
还会继续维护吗？

### ISSUE THREAD

**Issue by Jengro777** [treexi/wework#20]
很多这种类型的开源项目，都好几年没有维护了， 这个项目会持续维护吗

**Comment by treexi** [comment]
现在有什么问题吗？

**Comment by Jengro777** [comment]
> 现在有什么问题吗？

部署不了，docker 也部署不了

**Comment by Jengro777** [comment]
可以给一个 一键部署的命令吗？ 不需要设置任何东西

**Comment by Jengro777** [comment]
docker 的就可以

**Comment by Jengro777** [comment]
![image](https://github.com/appspa/app-space/assets/35259040/dd7e2020-264a-41f9-9ee0-a5863da04520)

**Comment by Jengro777** [comment]
可以提供一个 docker hub 的镜像吗？

**Comment by Jengro777** [comment]
![image](https://github.com/appspa/app-space/assets/35259040/a4a9aa11-4546-47a5-bb6e-3b052ae04824)

**Comment by treexi** [comment]
用源码部署
