### ISSUE TITLE
提供一个轻量化的基于sqlite的版本

### ISSUE THREAD

**Issue by rdself** [treexi/wework#25]
可否提供一个轻量化的基于sqlite的版本方便部署到低性能的机器上？感谢！

**Comment by shiftu** [comment]
我也需要

**Comment by cupen** [comment]
谁需要谁提 pr .

**Comment by cupen** [comment]
@RogerProSelf  用 docker 启动 mongodb 很容易的.
我加了一个 `compose.yml`(见 https://github.com/appspa/app-space/pull/26), 执行 `docker compose up -d` 搞定.
